// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class BlogCategory
{
    public int BlogCategoryId { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}