// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class Conversation
{
    public int ConversationId { get; set; }

    public int? CustomerId { get; set; }

    public int? OwnerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User Owner { get; set; }
}