// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class Dish
{
    public int DishId { get; set; }

    public string Note { get; set; }

    public string DishName { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string Img { get; set; }

    public int? DishCategoryId { get; set; }

    public virtual DishCategory DishCategory { get; set; }

    public virtual ICollection<DishDetail> DishDetails { get; set; } = new List<DishDetail>();

    public virtual ICollection<MenuDish> MenuDishes { get; set; } = new List<MenuDish>();

    public virtual ICollection<OrderDetailCustom> OrderDetailCustoms { get; set; } = new List<OrderDetailCustom>();
}