// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class DishDetail
{
    public int DishDetailId { get; set; }

    public int? DishId { get; set; }

    public int? IngredientId { get; set; }

    public virtual Dish Dish { get; set; }

    public virtual Ingredient Ingredient { get; set; }
}