// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class DishCategory
{
    public int DishCategoryId { get; set; }

    public string DishCategoryName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Dish> Dishes { get; set; } = new List<Dish>();
}