// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class ExtraChargeCatalog
{
    public int ExtraChargeCatalogId { get; set; }

    public string ChargeType { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Unit { get; set; }

    public decimal? UnitPrice { get; set; }

    public string Status { get; set; }
    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<OrderDetailExtraCharge> OrderDetailExtraCharges { get; set; } = new List<OrderDetailExtraCharge>();
}