// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class FeedbackMenu
{
    public int FeedbackMenuId { get; set; }

    public int? MenuId { get; set; }

    public int? CustomerId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual Menu Menu { get; set; }
}