// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class FeedbackService
{
    public int FeedbackServiceId { get; set; }

    public int? OrderId { get; set; }

    public int? OrderDetailId { get; set; }

    public int? ServiceId { get; set; }

    public int? CustomerId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public string Img { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual Order Order { get; set; }

    public virtual Service Service { get; set; }
}