// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class GuestDiscountTier
{
    public int GuestDiscountTierId { get; set; }

    public int MinGuestCount { get; set; }

    public decimal DiscountPercent { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}