// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class Ingredient
{
    public int IngredientId { get; set; }

    public string Description { get; set; }

    public string IngredientName { get; set; }

    public string Img { get; set; }

    public virtual ICollection<DishDetail> DishDetails { get; set; } = new List<DishDetail>();
}