// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class MenuDish
{
    public int MenuDishId { get; set; }

    public int? MenuId { get; set; }

    public int? DishId { get; set; }

    public virtual Dish Dish { get; set; }

    public virtual Menu Menu { get; set; }
}