// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class MenuCategory
{
    public int MenuCategoryId { get; set; }

    public string MenuCategoryName { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Menu> Menus { get; set; } = new List<Menu>();
}