// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class Menu
{
    public int MenuId { get; set; }

    public string MenuName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public decimal? BasePrice { get; set; }

    public string ImgUrl { get; set; }

    public string Status { get; set; }

    public int? MenuCategoryId { get; set; }

    public virtual ICollection<FeedbackMenu> FeedbackMenus { get; set; } = new List<FeedbackMenu>();

    public virtual MenuCategory MenuCategory { get; set; }

    public virtual ICollection<MenuDish> MenuDishes { get; set; } = new List<MenuDish>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PartyCategoryMenu> PartyCategoryMenus { get; set; } = new List<PartyCategoryMenu>();
}