// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class OrderDetailCustom
{
    public int OrderDetailCustomId { get; set; }

    public int? OrderDetailId { get; set; }

    public int? DishId { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Dish Dish { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}