// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class OrderDetailExtraCharge
{
    public int OrderDetailExtraChargeId { get; set; }

    public int? OrderDetailId { get; set; }

    public int? ExtraChargeCatalogId { get; set; }

    public string ChargeType { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Unit { get; set; }

    public decimal? UnitPrice { get; set; }

    public int? Quantity { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Status { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? IncurredAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Image { get; set; }

    public string Note { get; set; }

    public virtual User CreateByNavigation { get; set; }

    public virtual ExtraChargeCatalog ExtraChargeCatalog { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}