// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class OrderDetailStaffTask
{
    public int TaskId { get; set; }

    public int? OrderDetailId { get; set; }

    public int TaskTemplateId { get; set; }

    public string TaskName { get; set; }

    public int? StaffId { get; set; }

    public string TaskStatus { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Note { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual User Staff { get; set; }

    public virtual TaskTemplate TaskTemplate { get; set; }
}