// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int? OrderId { get; set; }

    public string Address { get; set; }

    public int? NumberOfGuests { get; set; }

    public string Status { get; set; }

    public decimal? TotalPrice { get; set; }

    public string Type { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? StaffGroupId { get; set; }

    public int? PartyCategoryId { get; set; }

    public int? MenuId { get; set; }

    public string NoteOrderDetail { get; set; }

    public string MenuSnapshot { get; set; }

    public string ServiceSnapshot { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderDetailCustom> OrderDetailCustoms { get; set; } = new List<OrderDetailCustom>();

    public virtual ICollection<OrderDetailExtraCharge> OrderDetailExtraCharges { get; set; } = new List<OrderDetailExtraCharge>();

    public virtual ICollection<OrderDetailStaffTask> OrderDetailStaffTasks { get; set; } = new List<OrderDetailStaffTask>();

    public virtual ICollection<OrderService> OrderServices { get; set; } = new List<OrderService>();

    public virtual PartyCategory PartyCategory { get; set; }

    public virtual StaffGroup StaffGroup { get; set; }
}