// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class OrderService
{
    public int OrderServiceId { get; set; }

    public int? OrderDetailId { get; set; }

    public int? ServiceId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? Quantity { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual Service Service { get; set; }
}