// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class PartyCategoryMenu
{
    public int PartyCategoryMenuId { get; set; }

    public int? PartyCategoryId { get; set; }

    public int? MenuId { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual PartyCategory PartyCategory { get; set; }
}