// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class PartyCategory
{
    public int PartyCategoryId { get; set; }

    public string PartyCategoryName { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? NumberOfGuests { get; set; }

    public string ImageUrl { get; set; }

    public int? ServiceDurationMinutes { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PartyCategoryMenu> PartyCategoryMenus { get; set; } = new List<PartyCategoryMenu>();
}