// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class PostBlock
{
    public int PostBlockId { get; set; }

    public int PostId { get; set; }

    public string Type { get; set; }

    public int Position { get; set; }

    public string Data { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Post Post { get; set; }
}