// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class Post
{
    public int PostId { get; set; }

    public int? BlogCategoryId { get; set; }

    public string Slug { get; set; }

    public string Title { get; set; }

    public string Excerpt { get; set; }

    public int? CoverImageId { get; set; }

    public string Status { get; set; }

    public DateTime? PublishedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual BlogCategory BlogCategory { get; set; }

    public virtual ICollection<PostBlock> PostBlocks { get; set; } = new List<PostBlock>();
}