// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class Service
{
    public int ServiceId { get; set; }

    public string ServiceName { get; set; }

    public string Description { get; set; }

    public decimal? BasePrice { get; set; }

    public string AisServiceSummary { get; set; }

    public string Status { get; set; }

    public string Img { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<FeedbackService> FeedbackServices { get; set; } = new List<FeedbackService>();

    public virtual ICollection<OrderService> OrderServices { get; set; } = new List<OrderService>();
}