// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class ServiceExtraChargeCatalog
{
    public int ServiceExtraChargeCatalogId { get; set; }

    public int ServiceId { get; set; }

    public int ExtraChargeCatalogId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ExtraChargeCatalog ExtraChargeCatalog { get; set; }

    public virtual Service Service { get; set; }
}