// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class StaffGroup
{
    public int StaffGroupId { get; set; }

    public string StaffGroupName { get; set; }

    public string Status { get; set; }

    public int? LeaderId { get; set; }

    public virtual User Leader { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<StaffGroupMember> StaffGroupMembers { get; set; } = new List<StaffGroupMember>();
}