// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class StaffGroupMember
{
    public int StaffGroupMemberId { get; set; }

    public int? StaffGroupId { get; set; }

    public int? StaffId { get; set; }

    public string Status { get; set; }

    public virtual User Staff { get; set; }

    public virtual StaffGroup StaffGroup { get; set; }
}