// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Status { get; set; }

    public string PasswordHash { get; set; }

    public string UserName { get; set; }

    public string Address { get; set; }

    public int? RoleId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Conversation> ConversationCustomers { get; set; } = new List<Conversation>();

    public virtual ICollection<Conversation> ConversationOwners { get; set; } = new List<Conversation>();

    public virtual ICollection<FeedbackMenu> FeedbackMenus { get; set; } = new List<FeedbackMenu>();

    public virtual ICollection<FeedbackService> FeedbackServices { get; set; } = new List<FeedbackService>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<OrderDetailStaffTask> OrderDetailStaffTasks { get; set; } = new List<OrderDetailStaffTask>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Role Role { get; set; }

    public virtual ICollection<StaffGroupMember> StaffGroupMembers { get; set; } = new List<StaffGroupMember>();

    public virtual ICollection<StaffGroup> StaffGroups { get; set; } = new List<StaffGroup>();
}