// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookfetSystem.Repositories.Entities;

public partial class UserDevice
{
    public int UserDeviceId { get; set; }

    public int UserId { get; set; }

    public string DeviceId { get; set; }

    public string ExpoPushToken { get; set; }

    public string Platform { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}