// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BookfetSystem.Repositories.Entities;
using Microsoft.EntityFrameworkCore;

namespace BookfetSystem.Repositories.DBContext;

public partial class GSP26SE10DBContext : DbContext
{
    public GSP26SE10DBContext(DbContextOptions<GSP26SE10DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BlogCategory> BlogCategories { get; set; }

    public virtual DbSet<ContactRequest> ContactRequests { get; set; }

    public virtual DbSet<Conversation> Conversations { get; set; }

    public virtual DbSet<Dish> Dishes { get; set; }

    public virtual DbSet<DishCategory> DishCategories { get; set; }

    public virtual DbSet<DishDetail> DishDetails { get; set; }

    public virtual DbSet<ExtraChargeCatalog> ExtraChargeCatalogs { get; set; }

    public virtual DbSet<FeedbackMenu> FeedbackMenus { get; set; }

    public virtual DbSet<FeedbackService> FeedbackServices { get; set; }

    public virtual DbSet<Ingredient> Ingredients { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuCategory> MenuCategories { get; set; }

    public virtual DbSet<MenuDish> MenuDishes { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderDetailCustom> OrderDetailCustoms { get; set; }

    public virtual DbSet<OrderDetailExtraCharge> OrderDetailExtraCharges { get; set; }

    public virtual DbSet<OrderDetailStaffTask> OrderDetailStaffTasks { get; set; }

    public virtual DbSet<OrderService> OrderServices { get; set; }

    public virtual DbSet<PartyCategory> PartyCategories { get; set; }

    public virtual DbSet<PartyCategoryMenu> PartyCategoryMenus { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostBlock> PostBlocks { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<StaffGroup> StaffGroups { get; set; }

    public virtual DbSet<StaffGroupMember> StaffGroupMembers { get; set; }

    public virtual DbSet<TaskTemplate> TaskTemplates { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDevice> UserDevices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BlogCategory>(entity =>
        {
            entity.HasKey(e => e.BlogCategoryId).HasName("blog_category_pkey");

            entity.ToTable("blog_category");

            entity.HasIndex(e => e.Slug, "blog_category_slug_key").IsUnique();

            entity.Property(e => e.BlogCategoryId).HasColumnName("blog_category_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("name");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("slug");
        });

        modelBuilder.Entity<ContactRequest>(entity =>
        {
            entity.HasKey(e => e.ContactRequestId).HasName("contact_request_pkey");

            entity.ToTable("contact_request");

            entity.Property(e => e.ContactRequestId).HasColumnName("contact_request_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .HasColumnName("full_name");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Subject)
                .HasMaxLength(255)
                .HasColumnName("subject");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Customer).WithMany(p => p.ContactRequests)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("contact_request_customer_id_fkey");
        });

        modelBuilder.Entity<Conversation>(entity =>
        {
            entity.HasKey(e => e.ConversationId).HasName("conversation_pkey");

            entity.ToTable("conversation");

            entity.Property(e => e.ConversationId).HasColumnName("conversation_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");

            entity.HasOne(d => d.Customer).WithMany(p => p.ConversationCustomers)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("conversation_customer_id_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.ConversationOwners)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("conversation_owner_id_fkey");
        });

        modelBuilder.Entity<Dish>(entity =>
        {
            entity.HasKey(e => e.DishId).HasName("dish_pkey");

            entity.ToTable("dish");

            entity.Property(e => e.DishId).HasColumnName("dish_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DishCategoryId).HasColumnName("dish_category_id");
            entity.Property(e => e.DishName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("dish_name");
            entity.Property(e => e.Img)
                .HasMaxLength(255)
                .HasColumnName("img");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Price)
                .HasPrecision(12, 2)
                .HasColumnName("price");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.DishCategory).WithMany(p => p.Dishes)
                .HasForeignKey(d => d.DishCategoryId)
                .HasConstraintName("dish_dish_category_id_fkey");
        });

        modelBuilder.Entity<DishCategory>(entity =>
        {
            entity.HasKey(e => e.DishCategoryId).HasName("dish_category_pkey");

            entity.ToTable("dish_category");

            entity.Property(e => e.DishCategoryId).HasColumnName("dish_category_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DishCategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("dish_category_name");
        });

        modelBuilder.Entity<DishDetail>(entity =>
        {
            entity.HasKey(e => e.DishDetailId).HasName("dish_detail_pkey");

            entity.ToTable("dish_detail");

            entity.Property(e => e.DishDetailId).HasColumnName("dish_detail_id");
            entity.Property(e => e.DishId).HasColumnName("dish_id");
            entity.Property(e => e.IngredientId).HasColumnName("ingredient_id");

            entity.HasOne(d => d.Dish).WithMany(p => p.DishDetails)
                .HasForeignKey(d => d.DishId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("dish_detail_dish_id_fkey");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.DishDetails)
                .HasForeignKey(d => d.IngredientId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("dish_detail_ingredient_id_fkey");
        });

        modelBuilder.Entity<ExtraChargeCatalog>(entity =>
        {
            entity.HasKey(e => e.ExtraChargeCatalogId).HasName("extra_charge_catalog_pkey");

            entity.ToTable("extra_charge_catalog");

            entity.Property(e => e.ExtraChargeCatalogId).HasColumnName("extra_charge_catalog_id");
            entity.Property(e => e.ChargeType)
                .HasMaxLength(100)
                .HasColumnName("charge_type");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Unit)
                .HasMaxLength(50)
                .HasColumnName("unit");
            entity.Property(e => e.UnitPrice)
                .HasPrecision(12, 2)
                .HasColumnName("unit_price");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<FeedbackMenu>(entity =>
        {
            entity.HasKey(e => e.FeedbackMenuId).HasName("feedback_menu_pkey");

            entity.ToTable("feedback_menu");

            entity.Property(e => e.FeedbackMenuId).HasColumnName("feedback_menu_id");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Img)
                .HasColumnType("jsonb")
                .HasColumnName("img");
            entity.Property(e => e.MenuId).HasColumnName("menu_id");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Customer).WithMany(p => p.FeedbackMenus)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("feedback_menu_customer_id_fkey");

            entity.HasOne(d => d.Menu).WithMany(p => p.FeedbackMenus)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("feedback_menu_menu_id_fkey");

            entity.HasOne(d => d.Order).WithMany(p => p.FeedbackMenus)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("feedback_menu_order_id_fkey");
        });

        modelBuilder.Entity<FeedbackService>(entity =>
        {
            entity.HasKey(e => e.FeedbackServiceId).HasName("feedback_service_pkey");

            entity.ToTable("feedback_service");

            entity.Property(e => e.FeedbackServiceId).HasColumnName("feedback_service_id");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Img)
                .HasColumnType("jsonb")
                .HasColumnName("img");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Customer).WithMany(p => p.FeedbackServices)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("feedback_service_customer_id_fkey");

            entity.HasOne(d => d.Order).WithMany(p => p.FeedbackServices)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("feedback_service_order_id_fkey");

            entity.HasOne(d => d.Service).WithMany(p => p.FeedbackServices)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("feedback_service_service_id_fkey");
        });

        modelBuilder.Entity<Ingredient>(entity =>
        {
            entity.HasKey(e => e.IngredientId).HasName("ingredient_pkey");

            entity.ToTable("ingredient");

            entity.Property(e => e.IngredientId).HasColumnName("ingredient_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Img)
                .HasMaxLength(255)
                .HasColumnName("img");
            entity.Property(e => e.IngredientName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("ingredient_name");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.MenuId).HasName("menu_pkey");

            entity.ToTable("menu");

            entity.Property(e => e.MenuId).HasColumnName("menu_id");
            entity.Property(e => e.AisMenuSummary).HasColumnName("ais_menu_summary");
            entity.Property(e => e.BasePrice)
                .HasPrecision(12, 2)
                .HasColumnName("base_price");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.ImgUrl)
                .HasColumnType("jsonb")
                .HasColumnName("img_url");
            entity.Property(e => e.MenuCategoryId).HasColumnName("menu_category_id");
            entity.Property(e => e.MenuName)
                .HasMaxLength(150)
                .HasColumnName("menu_name");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.MenuCategory).WithMany(p => p.Menus)
                .HasForeignKey(d => d.MenuCategoryId)
                .HasConstraintName("menu_menu_category_id_fkey");
        });

        modelBuilder.Entity<MenuCategory>(entity =>
        {
            entity.HasKey(e => e.MenuCategoryId).HasName("menu_category_pkey");

            entity.ToTable("menu_category");

            entity.Property(e => e.MenuCategoryId).HasColumnName("menu_category_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.MenuCategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("menu_category_name");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
        });

        modelBuilder.Entity<MenuDish>(entity =>
        {
            entity.HasKey(e => e.MenuDishId).HasName("menu_dish_pkey");

            entity.ToTable("menu_dish");

            entity.HasIndex(e => new { e.MenuId, e.DishId }, "menu_dish_menu_id_dish_id_key").IsUnique();

            entity.Property(e => e.MenuDishId).HasColumnName("menu_dish_id");
            entity.Property(e => e.DishId).HasColumnName("dish_id");
            entity.Property(e => e.MenuId).HasColumnName("menu_id");

            entity.HasOne(d => d.Dish).WithMany(p => p.MenuDishes)
                .HasForeignKey(d => d.DishId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("menu_dish_dish_id_fkey");

            entity.HasOne(d => d.Menu).WithMany(p => p.MenuDishes)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("menu_dish_menu_id_fkey");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("message_pkey");

            entity.ToTable("message");

            entity.Property(e => e.MessageId).HasColumnName("message_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.ConversationId).HasColumnName("conversation_id");
            entity.Property(e => e.MenuId).HasColumnName("menu_id");
            entity.Property(e => e.MessageType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValueSql("'TEXT'::character varying")
                .HasColumnName("message_type");
            entity.Property(e => e.SenderId).HasColumnName("sender_id");
            entity.Property(e => e.SentAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("sent_at");

            entity.HasOne(d => d.Conversation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ConversationId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("message_conversation_id_fkey");

            entity.HasOne(d => d.Menu).WithMany(p => p.Messages)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("message_menu_id_fkey");

            entity.HasOne(d => d.Sender).WithMany(p => p.Messages)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("message_sender_id_fkey");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("notification_pkey");

            entity.ToTable("notification");

            entity.Property(e => e.NotificationId).HasColumnName("notification_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.IsRead)
                .HasDefaultValue(false)
                .HasColumnName("is_read");
            entity.Property(e => e.IsSent)
                .HasDefaultValue(false)
                .HasColumnName("is_sent");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("notification_user_id_fkey");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("orders_pkey");

            entity.ToTable("orders");

            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.DepositAmount)
                .HasPrecision(12, 2)
                .HasColumnName("deposit_amount");
            entity.Property(e => e.MtdZlp)
                .HasColumnType("jsonb")
                .HasColumnName("mtd_zlp");
            entity.Property(e => e.NoteOrder).HasColumnName("note_order");
            entity.Property(e => e.RemainingAmount)
                .HasPrecision(12, 2)
                .HasColumnName("remaining_amount");
            entity.Property(e => e.ReviewedAt).HasColumnName("reviewed_at");
            entity.Property(e => e.ReviewedBy).HasColumnName("reviewed_by");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalPrice)
                .HasPrecision(12, 2)
                .HasColumnName("total_price");

            entity.HasOne(d => d.Customer).WithMany(p => p.OrderCustomers)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("orders_customer_id_fkey");

            entity.HasOne(d => d.ReviewedByNavigation).WithMany(p => p.OrderReviewedByNavigations)
                .HasForeignKey(d => d.ReviewedBy)
                .HasConstraintName("orders_reviewed_by_fkey");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("order_detail_pkey");

            entity.ToTable("order_detail");

            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.CustomDishSnapshot)
                .HasColumnType("jsonb")
                .HasColumnName("custom_dish_snapshot");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.MenuId).HasColumnName("menu_id");
            entity.Property(e => e.MenuSnapshot)
                .HasColumnType("jsonb")
                .HasColumnName("menu_snapshot");
            entity.Property(e => e.NoteOrderDetail).HasColumnName("note_order_detail");
            entity.Property(e => e.NumberOfGuests).HasColumnName("number_of_guests");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.PartyCategoryId).HasColumnName("party_category_id");
            entity.Property(e => e.ServiceSnapshot)
                .HasColumnType("jsonb")
                .HasColumnName("service_snapshot");
            entity.Property(e => e.StaffGroupId).HasColumnName("staff_group_id");
            entity.Property(e => e.StartTime).HasColumnName("start_time");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalPrice)
                .HasPrecision(12, 2)
                .HasColumnName("total_price");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");

            entity.HasOne(d => d.Menu).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.MenuId)
                .HasConstraintName("order_detail_menu_id_fkey");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("order_detail_order_id_fkey");

            entity.HasOne(d => d.PartyCategory).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.PartyCategoryId)
                .HasConstraintName("order_detail_party_category_id_fkey");

            entity.HasOne(d => d.StaffGroup).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.StaffGroupId)
                .HasConstraintName("order_detail_staff_group_id_fkey");
        });

        modelBuilder.Entity<OrderDetailCustom>(entity =>
        {
            entity.HasKey(e => e.OrderDetailCustomId).HasName("order_detail_custom_pkey");

            entity.ToTable("order_detail_custom");

            entity.Property(e => e.OrderDetailCustomId).HasColumnName("order_detail_custom_id");
            entity.Property(e => e.DishId).HasColumnName("dish_id");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.TotalAmount)
                .HasPrecision(12, 2)
                .HasColumnName("total_amount");

            entity.HasOne(d => d.Dish).WithMany(p => p.OrderDetailCustoms)
                .HasForeignKey(d => d.DishId)
                .HasConstraintName("order_detail_custom_dish_id_fkey");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.OrderDetailCustoms)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("order_detail_custom_order_detail_id_fkey");
        });

        modelBuilder.Entity<OrderDetailExtraCharge>(entity =>
        {
            entity.HasKey(e => e.OrderDetailExtraChargeId).HasName("order_detail_extra_charge_pkey");

            entity.ToTable("order_detail_extra_charge");

            entity.Property(e => e.OrderDetailExtraChargeId).HasColumnName("order_detail_extra_charge_id");
            entity.Property(e => e.ChargeType)
                .HasMaxLength(100)
                .HasColumnName("charge_type");
            entity.Property(e => e.CreateBy).HasColumnName("create_by");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ExtraChargeCatalogId).HasColumnName("extra_charge_catalog_id");
            entity.Property(e => e.Image)
                .HasColumnType("jsonb")
                .HasColumnName("image");
            entity.Property(e => e.IncurredAt).HasColumnName("incurred_at");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.TotalAmount)
                .HasPrecision(12, 2)
                .HasColumnName("total_amount");
            entity.Property(e => e.Unit)
                .HasMaxLength(50)
                .HasColumnName("unit");
            entity.Property(e => e.UnitPrice)
                .HasPrecision(12, 2)
                .HasColumnName("unit_price");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.OrderDetailExtraCharges)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("order_detail_extra_charge_create_by_fkey");

            entity.HasOne(d => d.ExtraChargeCatalog).WithMany(p => p.OrderDetailExtraCharges)
                .HasForeignKey(d => d.ExtraChargeCatalogId)
                .HasConstraintName("order_detail_extra_charge_extra_charge_catalog_id_fkey");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.OrderDetailExtraCharges)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("order_detail_extra_charge_order_detail_id_fkey");
        });

        modelBuilder.Entity<OrderDetailStaffTask>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("order_detail_staff_task_pkey");

            entity.ToTable("order_detail_staff_task");

            entity.Property(e => e.TaskId).HasColumnName("task_id");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.StaffId).HasColumnName("staff_id");
            entity.Property(e => e.StartTime).HasColumnName("start_time");
            entity.Property(e => e.TaskName)
                .HasMaxLength(255)
                .HasColumnName("task_name");
            entity.Property(e => e.TaskStatus)
                .HasMaxLength(50)
                .HasColumnName("task_status");
            entity.Property(e => e.TaskTemplateId).HasColumnName("task_template_id");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.OrderDetailStaffTasks)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("order_detail_staff_task_order_detail_id_fkey");

            entity.HasOne(d => d.Staff).WithMany(p => p.OrderDetailStaffTasks)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("order_detail_staff_task_staff_id_fkey");

            entity.HasOne(d => d.TaskTemplate).WithMany(p => p.OrderDetailStaffTasks)
                .HasForeignKey(d => d.TaskTemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("order_detail_staff_task_task_template_id_fkey");
        });

        modelBuilder.Entity<OrderService>(entity =>
        {
            entity.HasKey(e => e.OrderServiceId).HasName("order_service_pkey");

            entity.ToTable("order_service");

            entity.Property(e => e.OrderServiceId).HasColumnName("order_service_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.OrderServices)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("order_service_order_detail_id_fkey");

            entity.HasOne(d => d.Service).WithMany(p => p.OrderServices)
                .HasForeignKey(d => d.ServiceId)
                .HasConstraintName("order_service_service_id_fkey");
        });

        modelBuilder.Entity<PartyCategory>(entity =>
        {
            entity.HasKey(e => e.PartyCategoryId).HasName("party_category_pkey");

            entity.ToTable("party_category");

            entity.Property(e => e.PartyCategoryId).HasColumnName("party_category_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .HasColumnName("image_url");
            entity.Property(e => e.NumberOfGuests).HasColumnName("number_of_guests");
            entity.Property(e => e.PartyCategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("party_category_name");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
        });

        modelBuilder.Entity<PartyCategoryMenu>(entity =>
        {
            entity.HasKey(e => e.PartyCategoryMenuId).HasName("party_category_menu_pkey");

            entity.ToTable("party_category_menu");

            entity.HasIndex(e => new { e.PartyCategoryId, e.MenuId }, "party_category_menu_party_category_id_menu_id_key").IsUnique();

            entity.Property(e => e.PartyCategoryMenuId).HasColumnName("party_category_menu_id");
            entity.Property(e => e.MenuId).HasColumnName("menu_id");
            entity.Property(e => e.PartyCategoryId).HasColumnName("party_category_id");

            entity.HasOne(d => d.Menu).WithMany(p => p.PartyCategoryMenus)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("party_category_menu_menu_id_fkey");

            entity.HasOne(d => d.PartyCategory).WithMany(p => p.PartyCategoryMenus)
                .HasForeignKey(d => d.PartyCategoryId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("party_category_menu_party_category_id_fkey");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("payment_pkey");

            entity.ToTable("payment");

            entity.Property(e => e.PaymentId).HasColumnName("payment_id");
            entity.Property(e => e.Amount)
                .HasPrecision(12, 2)
                .HasColumnName("amount");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.PaidAt).HasColumnName("paid_at");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(50)
                .HasColumnName("payment_status");
            entity.Property(e => e.PaymentType)
                .HasMaxLength(50)
                .HasColumnName("payment_type");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("payment_order_id_fkey");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("post_pkey");

            entity.ToTable("post");

            entity.HasIndex(e => e.Slug, "post_slug_key").IsUnique();

            entity.Property(e => e.PostId).HasColumnName("post_id");
            entity.Property(e => e.BlogCategoryId).HasColumnName("blog_category_id");
            entity.Property(e => e.Coverimage)
                .HasColumnType("jsonb")
                .HasColumnName("coverimage");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Excerpt).HasColumnName("excerpt");
            entity.Property(e => e.PublishedAt).HasColumnName("published_at");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("slug");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.BlogCategory).WithMany(p => p.Posts)
                .HasForeignKey(d => d.BlogCategoryId)
                .HasConstraintName("post_blog_category_id_fkey");
        });

        modelBuilder.Entity<PostBlock>(entity =>
        {
            entity.HasKey(e => e.PostBlockId).HasName("post_block_pkey");

            entity.ToTable("post_block");

            entity.Property(e => e.PostBlockId).HasColumnName("post_block_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Position).HasColumnName("position");
            entity.Property(e => e.PostId).HasColumnName("post_id");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Post).WithMany(p => p.PostBlocks)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("post_block_post_id_fkey");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("role_pkey");

            entity.ToTable("role");

            entity.HasIndex(e => e.RoleName, "role_role_name_key").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("service_pkey");

            entity.ToTable("service");

            entity.Property(e => e.ServiceId).HasColumnName("service_id");
            entity.Property(e => e.AisServiceSummary).HasColumnName("ais_service_summary");
            entity.Property(e => e.BasePrice)
                .HasPrecision(12, 2)
                .HasColumnName("base_price");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Img)
                .HasMaxLength(255)
                .HasColumnName("img");
            entity.Property(e => e.ServiceName)
                .HasMaxLength(100)
                .HasColumnName("service_name");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
        });

        modelBuilder.Entity<StaffGroup>(entity =>
        {
            entity.HasKey(e => e.StaffGroupId).HasName("staff_group_pkey");

            entity.ToTable("staff_group");

            entity.Property(e => e.StaffGroupId).HasColumnName("staff_group_id");
            entity.Property(e => e.LeaderId).HasColumnName("leader_id");
            entity.Property(e => e.StaffGroupName)
                .HasMaxLength(100)
                .HasColumnName("staff_group_name");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Leader).WithMany(p => p.StaffGroups)
                .HasForeignKey(d => d.LeaderId)
                .HasConstraintName("staff_group_leader_id_fkey");
        });

        modelBuilder.Entity<StaffGroupMember>(entity =>
        {
            entity.HasKey(e => e.StaffGroupMemberId).HasName("staff_group_member_pkey");

            entity.ToTable("staff_group_member");

            entity.HasIndex(e => new { e.StaffGroupId, e.StaffId }, "staff_group_member_staff_group_id_staff_id_key").IsUnique();

            entity.Property(e => e.StaffGroupMemberId).HasColumnName("staff_group_member_id");
            entity.Property(e => e.StaffGroupId).HasColumnName("staff_group_id");
            entity.Property(e => e.StaffId).HasColumnName("staff_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.StaffGroup).WithMany(p => p.StaffGroupMembers)
                .HasForeignKey(d => d.StaffGroupId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("staff_group_member_staff_group_id_fkey");

            entity.HasOne(d => d.Staff).WithMany(p => p.StaffGroupMembers)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("staff_group_member_staff_id_fkey");
        });

        modelBuilder.Entity<TaskTemplate>(entity =>
        {
            entity.HasKey(e => e.TaskTemplateId).HasName("task_template_pkey");

            entity.ToTable("task_template");

            entity.Property(e => e.TaskTemplateId).HasColumnName("task_template_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.TaskName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("task_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Owner).WithMany(p => p.TaskTemplates)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("task_template_owner_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "users_email_key").IsUnique();

            entity.HasIndex(e => e.UserName, "users_user_name_key").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.Avatar)
                .HasMaxLength(255)
                .HasColumnName("avatar");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .HasColumnName("full_name");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .HasColumnName("user_name");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("users_role_id_fkey");
        });

        modelBuilder.Entity<UserDevice>(entity =>
        {
            entity.HasKey(e => e.UserDeviceId).HasName("user_device_pkey");

            entity.ToTable("user_device");

            entity.HasIndex(e => e.ExpoPushToken, "user_device_expo_push_token_key").IsUnique();

            entity.HasIndex(e => new { e.UserId, e.DeviceId }, "user_device_user_id_device_id_key").IsUnique();

            entity.Property(e => e.UserDeviceId).HasColumnName("user_device_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.DeviceId)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("device_id");
            entity.Property(e => e.ExpoPushToken)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("expo_push_token");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Platform)
                .HasMaxLength(50)
                .HasColumnName("platform");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.UserDevices)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_device_user_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}