name: Auto Deploy to Local Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          cd BookfetSystem/BookfetSystem.API
          dotnet publish -c Release -o publish

      - name: Kill old app
        shell: powershell
        run: |
         $port = 5121
          $connections = netstat -ano | Select-String ":$port"
          foreach ($conn in $connections) {
          $parts = $conn -split "\s+"
          $pid = $parts[-1]
          Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
          }
          

      - name: Start new app
        shell: powershell
        run: |
          $projectDir = "$env:GITHUB_WORKSPACE/BookfetSystem/BookfetSystem.API"
          cd $projectDir
          start cmd /c "dotnet run --configuration Release"