name: Auto Deploy to Local Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          cd BookfetSystem/BookfetSystem.API
          dotnet publish -c Release -o publish

      - name: Kill old API (force by port)
        shell: powershell
        run: |
          $port = 5121

          $connections = netstat -ano | findstr ":$port" | findstr "LISTENING"

          if ($connections) {
          $processIds = $connections | ForEach-Object {
          ($_ -split "\s+")[-1]
          } | Sort-Object -Unique

           foreach ($procId in $processIds) {
           if ($procId -ne "0" -and $procId -ne "4") {
            Write-Host "Killing PID $procId"
            taskkill /F /PID $procId /T
            }
           }
          } else {
           Write-Host "No LISTENING process on port $port"
          }

      - name: Start new app
        shell: powershell
        run: |
          $projectDir = "$env:GITHUB_WORKSPACE/BookfetSystem/BookfetSystem.API"

          Start-Process -FilePath "dotnet" `
            -ArgumentList "run --configuration Release" `
            -WorkingDirectory $projectDir
